######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 8 16:45:06 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sim.h temp.h
SOURCES += sim.cpp temp.cpp

QMAKE_CXXFLAGS += -g -std=c++0x
